# .github/workflows/ci-docker-build.yml
name: CI – Docker Build Check

on:
  pull_request:
    branches: [dev]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build client Docker image
        id: client_build
        continue-on-error: true
        run: |
          set +e
          docker build -f client/Dockerfile -t client-check client/ > client_build.log 2>&1
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT

      - name: Build server Docker image
        id: server_build
        continue-on-error: true
        run: |
          set +e
          docker build -f server/Dockerfile -t server-check server/ > server_build.log 2>&1
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT

      - name: Create issue on Docker build failure
        if: ${{ steps.client_build.outputs.exit_code != '0' || steps.server_build.outputs.exit_code != '0' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const pr = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            const clientExit = ${{ steps.client_build.outputs.exit_code }};
            const serverExit = ${{ steps.server_build.outputs.exit_code }};
            const clientLog = fs.readFileSync('client_build.log', 'utf8');
            const serverLog = fs.readFileSync('server_build.log', 'utf8');

            const body = `
            ## Docker build failed on PR #${pr}

            **Client build** – exit code: ${clientExit}
            \`\`\`
            ${clientLog}
            \`\`\`

            **Server build** – exit code: ${serverExit}
            \`\`\`
            ${serverLog}
            \`\`\`
            `;

            await github.rest.issues.create({
              owner,
              repo,
              title: `Docker build failed on PR #${pr}`,
              body,
              labels: ['ci','docker-build-failure']
            });
