# .github/workflows/ci-docker-build.yml
name: CI – Docker Build Check

on:
  pull_request:
    branches:
      - dev

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build client Docker image
        id: client_build
        continue-on-error: true
        run: |
          set +e
          docker build -f client/Dockerfile -t client-check client/ > client_build.log 2>&1
          EXIT_CODE=$?
          # expose exit code pour la condition suivante
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT

      - name: Build server Docker image
        id: server_build
        continue-on-error: true
        run: |
          set +e
          docker build -f server/Dockerfile -t server-check server/ > server_build.log 2>&1
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT

      - name: Create issue on Docker build failure
        if: ${{ steps.client_build.outputs.exit_code != '0' || steps.server_build.outputs.exit_code != '0' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;

            // lecture des logs
            const clientLog = fs.readFileSync('client_build.log', 'utf8');
            const serverLog = fs.readFileSync('server_build.log', 'utf8');

            // corps de l’issue
            const body = `
            ## Docker build failed on PR #${prNumber}

            **Client build** – exit code: ${{ steps.client_build.outputs.exit_code }}
            \`\`\`
            ${clientLog}
            \`\`\`

            **Server build** – exit code: ${{ steps.server_build.outputs.exit_code }}
            \`\`\`
            ${serverLog}
            \`\`\`
            `;

            await github.issues.create({
              owner,
              repo,
              title: `Docker build failed on PR #${prNumber}`,
              body,
              labels: ['ci', 'docker-build-failure'],
            });
